server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - PrefixPath=/
      routes:
        # =================
        - id: user
          uri: http://localhost:8085/users
          predicates:
            - Path=/users/**
#          filters:
#            - StripPrefix=1
        # =================
        - id: account
          uri: http://localhost:8086/bankaccounts
          predicates:
            - Path=/bankaccounts/**
#          filters:
#            - StripPrefix=1



